= Vert.x Kafka AdminUtils
:toc: left
:lang: js
:js: js

This component provides a vert.x wrapper around the most important functions of Kafka's AdminUtils.

AdminUtils are used to create, modify, and delete topics. Other functionality covered by AdminUtils,
but not this wrapper, includes Partition Management, Broker Configuration management, etc.

== Using the AdminUtils

=== Create a topic

You can call `link:../../jsdoc/module-vertx-kafka-client-js_admin_utils-AdminUtils.html#createTopic[createTopic]` to create a topic.
Parameters are: topic name, number of partitions, number of replicas, and the usual callback to handle the result.
It might return an error, e.g. if the number of requested replicas is greater than the number of brokers.

[source,js]
----
var Vertx = require("vertx-js/vertx");
var AdminUtils = require("vertx-kafka-client-js/admin_utils");
var adminUtils = AdminUtils.create(Vertx.vertx(), "localhost:2181", true);
// Create topic 'myNewTopic' with 2 partition and 1 replicas
adminUtils.createTopic("myNewTopic", 2, 1, function (result, result_err) {
  if (result_err == null) {
    console.log("Creation of topic myNewTopic successful!")} else {
    console.log("Creation of topic myNewTopic failed: " + result_err.getLocalizedMessage())}
});

----

=== Delete a topic

You can call `link:../../jsdoc/module-vertx-kafka-client-js_admin_utils-AdminUtils.html#deleteTopic[deleteTopic]` to delete a topic.
Parameters are: topic name, and the usual callback to handle the result.
It might return an error, e.g. if the topic does not exist.

[source,js]
----
var Vertx = require("vertx-js/vertx");
var AdminUtils = require("vertx-kafka-client-js/admin_utils");
var adminUtils = AdminUtils.create(Vertx.vertx(), "localhost:2181", true);
// Delete topic 'myNewTopic'
adminUtils.deleteTopic("myNewTopic", function (result, result_err) {
  if (result_err == null) {
    console.log("Deletion of topic myNewTopic successful!")} else {
    console.log("Deletion of topic myNewTopic failed: " + result_err.getLocalizedMessage())}
});

----

=== Change a topic's configuration

If you need to update the configuration of a topic, e.g., you want to update the retention policy,
you can call `link:../../jsdoc/module-vertx-kafka-client-js_admin_utils-AdminUtils.html#changeTopicConfig[changeTopicConfig]` to update a topic.
Parameters are: topic name, a Map (String -> String) with parameters to be changed,
and the usual callback to handle the result.
It might return an error, e.g. if the topic does not exist.

[source,js]
----
var Vertx = require("vertx-js/vertx");
var AdminUtils = require("vertx-kafka-client-js/admin_utils");
var adminUtils = AdminUtils.create(Vertx.vertx(), "localhost:2181", true);
// Set retention to 1000 ms and max size of the topic partition to 1 kiByte
var properties = {};
properties["delete.retention.ms"] = "1000";
properties["retention.bytes"] = "1024";
adminUtils.changeTopicConfig("myNewTopic", properties, function (result, result_err) {
  if (result_err == null) {
    console.log("Configuration change of topic myNewTopic successful!")} else {
    console.log("Configuration change of topic myNewTopic failed: " + result_err.getLocalizedMessage())}
});
}
----

=== Check if a topic exists

If you want to check if a topic exists, you can call `link:../../jsdoc/module-vertx-kafka-client-js_admin_utils-AdminUtils.html#topicExists[topicExists]`.
Parameters are: topic name, and the usual callback to handle the result.
It might return an error, e.g. if the topic does not exist.

[source,js]
----
var Vertx = require("vertx-js/vertx");
var AdminUtils = require("vertx-kafka-client-js/admin_utils");
var adminUtils = AdminUtils.create(Vertx.vertx(), "localhost:2181", true);
adminUtils.topicExists("myNewTopic", function (result, result_err) {
  if (result_err == null) {
    console.log("Topic myNewTopic exists: " + result);
  } else {
    console.log("Failed to check if topic myNewTopic exists: " + result_err.getLocalizedMessage())}
});

----