= Vert.x Kafka client
:toc: left
:lang: ruby
:ruby: ruby

This component provides a Kafka client for reading and sending messages from/to an link:https://kafka.apache.org/[Apache Kafka] cluster.

As consumer, the API provides methods for subscribing to a topic partition receiving
messages asynchronously or reading them as a stream (even with the possibility to pause/resume the stream).

As producer, the API provides methods for sending message to a topic partition like writing on a stream.

WARNING: this module has the tech preview status, this means the API can change between versions.

== Using the Vert.x Kafka client

To use this component, add the following dependency to the dependencies section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-kafka-client</artifactId>
  <version>3.5.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile io.vertx:vertx-kafka-client:3.5.0-SNAPSHOT
----

== Creating Kafka clients

Creating consumers and producers is quite similar and on how it works using the native Kafka client library.

They need to be configured with a bunch of properties as described in the official
Apache Kafka documentation, for the link:https://kafka.apache.org/documentation/#newconsumerconfigs[consumer] and
for the link:https://kafka.apache.org/documentation/#producerconfigs[producer].

To achieve that, a map can be configured with such properties passing it to one of the
static creation methods exposed by `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html[KafkaConsumer]` and
`link:../../yardoc/VertxKafkaClient/KafkaProducer.html[KafkaProducer]`

[source,ruby]
----
require 'vertx-kafka-client/kafka_consumer'

# creating the consumer using map config
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.deserializer"] = "org.apache.kafka.common.serialization.StringDeserializer"
config["value.deserializer"] = "org.apache.kafka.common.serialization.StringDeserializer"
config["group.id"] = "my_group"
config["auto.offset.reset"] = "earliest"
config["enable.auto.commit"] = "false"

# use consumer for interacting with Apache Kafka
consumer = VertxKafkaClient::KafkaConsumer.create(vertx, config)

----

In the above example, a `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html[KafkaConsumer]` instance is created using
a map instance in order to specify the Kafka nodes list to connect (just one) and
the deserializers to use for getting key and value from each received message.

Likewise a producer can be created

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer'

# creating the producer using map and class types for key and value serializers/deserializers
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.serializer"] = "org.apache.kafka.common.serialization.StringSerializer"
config["value.serializer"] = "org.apache.kafka.common.serialization.StringSerializer"
config["acks"] = "1"

# use producer for interacting with Apache Kafka
producer = VertxKafkaClient::KafkaProducer.create(vertx, config)

----

ifdef::java,groovy,kotlin[]
Another way is to use a `link:unavailable[Properties]` instance instead of the map.

[source,ruby]
----
require 'vertx-kafka-client/kafka_consumer'

# creating the consumer using properties config
config = Java::JavaUtil::Properties.new()
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::BOOTSTRAP_SERVERS_CONFIG, "localhost:9092")
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::KEY_DESERIALIZER_CLASS_CONFIG, Java::OrgApacheKafkaCommonSerialization::StringDeserializer::class)
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::VALUE_DESERIALIZER_CLASS_CONFIG, Java::OrgApacheKafkaCommonSerialization::StringDeserializer::class)
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::GROUP_ID_CONFIG, "my_group")
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::AUTO_OFFSET_RESET_CONFIG, "earliest")
config.put(Java::OrgApacheKafkaClientsConsumer::ConsumerConfig::ENABLE_AUTO_COMMIT_CONFIG, "false")

# use consumer for interacting with Apache Kafka
consumer = VertxKafkaClient::KafkaConsumer.create(vertx, config)

----

More advanced creation methods allow to specify the class type for the key and the value used for sending messages
or provided by received messages; this is a way for setting the key and value serializers/deserializers instead of
using the related properties for that

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer'

# creating the producer using map and class types for key and value serializers/deserializers
config = Java::JavaUtil::Properties.new()
config.put(Java::OrgApacheKafkaClientsProducer::ProducerConfig::BOOTSTRAP_SERVERS_CONFIG, "localhost:9092")
config.put(Java::OrgApacheKafkaClientsProducer::ProducerConfig::ACKS_CONFIG, "1")

# use producer for interacting with Apache Kafka
producer = VertxKafkaClient::KafkaProducer.create(vertx, config, Java::JavaLang::String::class, Java::JavaLang::String::class)

----

Here the `link:../../yardoc/VertxKafkaClient/KafkaProducer.html[KafkaProducer]` instance is created in using a `link:unavailable[Properties]` for
specifying Kafka nodes list to connect (just one) and the acknowledgment mode; the key and value deserializers are
specified as parameters of `link:../../yardoc/VertxKafkaClient/KafkaProducer.html#create-class_method[KafkaProducer.create]`.
endif::[]

== Receiving messages from a topic joining a consumer group

In order to start receiving messages from Kafka topics, the consumer can use the
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#subscribe-instance_method[subscribe]` method for
subscribing to a set of topics being part of a consumer group (specified by the properties on creation).

You also need to register a handler for handling incoming messages using the
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#handler-instance_method[handler]`.

[source,ruby]
----

# register the handler for incoming messages
consumer.handler() { |record|
  puts "Processing key=#{record.key()},value=#{record.value()},partition=#{record.partition()},offset=#{record.offset()}"
}

# subscribe to several topics
topics = Java::JavaUtil::HashSet.new()
topics.add?("topic1")
topics.add?("topic2")
topics.add?("topic3")
consumer.subscribe(topics)

# or just subscribe to a single topic
consumer.subscribe("a-single-topic")

----

The handler can be registered before or after the call to `subscribe()`; messages won't be consumed until both
methods have been called. This allows you to call `subscribe()`, then `seek()` and finally `handler()` in
order to only consume messages starting from a particular offset, for example.

A handler can also be passed during subscription to be aware of the subscription result and being notified when the operation
is completed.

[source,ruby]
----

# register the handler for incoming messages
consumer.handler() { |record|
  puts "Processing key=#{record.key()},value=#{record.value()},partition=#{record.partition()},offset=#{record.offset()}"
}

# subscribe to several topics
topics = Java::JavaUtil::HashSet.new()
topics.add?("topic1")
topics.add?("topic2")
topics.add?("topic3")
consumer.subscribe(topics) { |ar_err,ar|
  if (ar_err == nil)
    puts "subscribed"
  else
    puts "Could not subscribe #{ar_err.get_message()}"
  end
}

# or just subscribe to a single topic
consumer.subscribe("a-single-topic") { |ar_err,ar|
  if (ar_err == nil)
    puts "subscribed"
  else
    puts "Could not subscribe #{ar_err.get_message()}"
  end
}

----

Using the consumer group way, the Kafka cluster assigns partitions to the consumer taking into account other connected
consumers in the same consumer group, so that partitions can be spread across them.

The Kafka cluster handles partitions re-balancing when a consumer leaves the group (so assigned partitions are free
to be assigned to other consumers) or a new consumer joins the group (so it wants partitions to read from).

You can register handlers on a `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html[KafkaConsumer]` to be notified
of the partitions revocations and assignments by the Kafka cluster using
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#partitions_revoked_handler-instance_method[partitionsRevokedHandler]` and
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#partitions_assigned_handler-instance_method[partitionsAssignedHandler]`.

[source,ruby]
----

# register the handler for incoming messages
consumer.handler() { |record|
  puts "Processing key=#{record.key()},value=#{record.value()},partition=#{record.partition()},offset=#{record.offset()}"
}

# registering handlers for assigned and revoked partitions
consumer.partitions_assigned_handler() { |topicPartitions|

  puts "Partitions assigned"
  topicPartitions.each do |topicPartition|
    puts "#{topicPartition['topic']} #{topicPartition['partition']}"
  end
}

consumer.partitions_revoked_handler() { |topicPartitions|

  puts "Partitions revoked"
  topicPartitions.each do |topicPartition|
    puts "#{topicPartition['topic']} #{topicPartition['partition']}"
  end
}

# subscribes to the topic
consumer.subscribe("test") { |ar_err,ar|

  if (ar_err == nil)
    puts "Consumer subscribed"
  end
}

----

After joining a consumer group for receiving messages, a consumer can decide to leave the consumer group in order to
not get messages anymore using `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#unsubscribe-instance_method[unsubscribe]`

[source,ruby]
----

# consumer is already member of a consumer group

# unsubscribing request
consumer.unsubscribe()

----

You can add an handler to be notified of the result

[source,ruby]
----

# consumer is already member of a consumer group

# unsubscribing request
consumer.unsubscribe() { |ar_err,ar|

  if (ar_err == nil)
    puts "Consumer unsubscribed"
  end
}

----

== Receiving messages from a topic requesting specific partitions

Besides being part of a consumer group for receiving messages from a topic, a consumer can ask for a specific
topic partition. When the consumer is not part part of a consumer group the overall application cannot
rely on the re-balancing feature.

You can use `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#assign-instance_method[assign]`
in order to ask for specific partitions.

[source,ruby]
----

# register the handler for incoming messages
consumer.handler() { |record|
  puts "key=#{record.key()},value=#{record.value()},partition=#{record.partition()},offset=#{record.offset()}"
}

#
topicPartitions = Java::JavaUtil::HashSet.new()
topicPartitions.add?({
  'topic' => "test",
  'partition' => 0
})

# requesting to be assigned the specific partition
consumer.assign(topicPartitions) { |done_err,done|

  if (done_err == nil)
    puts "Partition assigned"

    # requesting the assigned partitions
    consumer.assignment() { |done1_err,done1|

      if (done1_err == nil)

        done1.each do |topicPartition|
          puts "#{topicPartition['topic']} #{topicPartition['partition']}"
        end
      end
    }
  end
}

----

As with `subscribe()`, the handler can be registered before or after the call to `assign()`;
messages won't be consumed until both methods have been called. This allows you to call
`assign()`, then `seek()` and finally `handler()` in
order to only consume messages starting from a particular offset, for example.

Calling `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#assignment-instance_method[assignment]` provides
the list of the current assigned partitions.

== Getting topic partition information

You can call the `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#partitions_for-instance_method[partitionsFor]` to get information about
partitions for a specified topic

[source,ruby]
----

# asking partitions information about specific topic
consumer.partitions_for("test") { |ar_err,ar|

  if (ar_err == nil)

    ar.each do |partitionInfo|
      puts partitionInfo
    end
  end
}

----

In addition `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#list_topics-instance_method[listTopics]` provides all available topics
with related partitions

[source,ruby]
----

# asking information about available topics and related partitions
consumer.list_topics() { |ar_err,ar|

  if (ar_err == nil)

    map = ar
    map.each_pair { |topic,partitions|
      puts "topic = #{topic}"
      puts "partitions = #{map[topic]}"
    }
  end
}

----

== Manual offset commit

In Apache Kafka the consumer is in charge to handle the offset of the last read message.

This is executed by the commit operation executed automatically every time a bunch of messages are read
from a topic partition. The configuration parameter `enable.auto.commit` must be set to `true` when the
consumer is created.

Manual offset commit, can be achieved with `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#commit-instance_method[commit]`.
It can be used to achieve _at least once_ delivery to be sure that the read messages are processed before committing
the offset.

[source,ruby]
----

# consumer is processing read messages

# committing offset of the last read message
consumer.commit() { |ar_err,ar|

  if (ar_err == nil)
    puts "Last read message offset committed"
  end
}

----

== Seeking in a topic partition

Apache Kafka can retain messages for a long period of time and the consumer can seek inside a topic partition
and obtain arbitrary access to the messages.

You can use `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#seek-instance_method[seek]` to change the offset for reading at a specific
position

[source,ruby]
----

topicPartition = {
  'topic' => "test",
  'partition' => 0
}

# seek to a specific offset
consumer.seek(topicPartition, 10) { |done_err,done|

  if (done_err == nil)
    puts "Seeking done"
  end
}


----

When the consumer needs to re-read the stream from the beginning, it can use `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#seek_to_beginning-instance_method[seekToBeginning]`

[source,ruby]
----

topicPartition = {
  'topic' => "test",
  'partition' => 0
}

# seek to the beginning of the partition
consumer.seek_to_beginning(Java::JavaUtil::Collections.singleton(topicPartition)) { |done_err,done|

  if (done_err == nil)
    puts "Seeking done"
  end
}

----

Finally `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#seek_to_end-instance_method[seekToEnd]` can be used to come back at the end of the partition

[source,ruby]
----

topicPartition = {
  'topic' => "test",
  'partition' => 0
}

# seek to the end of the partition
consumer.seek_to_end(Java::JavaUtil::Collections.singleton(topicPartition)) { |done_err,done|

  if (done_err == nil)
    puts "Seeking done"
  end
}

----

== Offset lookup

You can use the beginningOffsets API introduced in Kafka 0.10.1.1 to get the first offset
for a given partition. In contrast to `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#seek_to_beginning-instance_method[seekToBeginning]`,
it does not change the consumer's offset.

[source,ruby]
----
topicPartitions = Java::JavaUtil::HashSet.new()
topicPartition = {
  'topic' => "test",
  'partition' => 0
}
topicPartitions.add?(topicPartition)

consumer.beginning_offsets(topicPartitions) { |done_err,done|
  if (done_err == nil)
    results = done
    results.each_pair { |topic,beginningOffset|
      puts "Beginning offset for topic=#{topic['topic']}, partition=#{topic['partition']}, beginningOffset=#{beginningOffset}"
    }
  end
}

# Convenience method for single-partition lookup
consumer.beginning_offsets(topicPartition) { |done_err,done|
  if (done_err == nil)
    beginningOffset = done
    puts "Beginning offset for topic=#{topicPartition['topic']}, partition=#{topicPartition['partition']}, beginningOffset=#{beginningOffset}"
  end
}


----

You can use the endOffsets API introduced in Kafka 0.10.1.1 to get the last offset
for a given partition. In contrast to `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#seek_to_end-instance_method[seekToEnd]`,
it does not change the consumer's offset.

[source,ruby]
----
topicPartitions = Java::JavaUtil::HashSet.new()
topicPartition = {
  'topic' => "test",
  'partition' => 0
}
topicPartitions.add?(topicPartition)

consumer.end_offsets(topicPartitions) { |done_err,done|
  if (done_err == nil)
    results = done
    results.each_pair { |topic,endOffset|
      puts "End offset for topic=#{topic['topic']}, partition=#{topic['partition']}, endOffset=#{endOffset}"
    }
  end
}

# Convenience method for single-partition lookup
consumer.end_offsets(topicPartition) { |done_err,done|
  if (done_err == nil)
    endOffset = done
    puts "End offset for topic=#{topicPartition['topic']}, partition=#{topicPartition['partition']}, endOffset=#{endOffset}"
  end
}

----

You can use the offsetsForTimes API introduced in Kafka 0.10.1.1 to look up an offset by
timestamp, i.e. search parameter is an epoch timestamp and the call returns the lowest offset
with ingestion timestamp >= given timestamp.

[source,ruby]
----
Code not translatable
----
== Message flow control

A consumer can control the incoming message flow and pause/resume the read operation from a topic, e.g it
can pause the message flow when it needs more time to process the actual messages and then resume
to continue message processing.

To achieve that you can use `link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#pause-instance_method[pause]` and
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#resume-instance_method[resume]`

[source,ruby]
----

topicPartition = {
  'topic' => "test",
  'partition' => 0
}

# registering the handler for incoming messages
consumer.handler() { |record|
  puts "key=#{record.key()},value=#{record.value()},partition=#{record.partition()},offset=#{record.offset()}"

  # i.e. pause/resume on partition 0, after reading message up to offset 5
  if ((record.partition() == 0) && (record.offset() == 5))

    # pause the read operations
    consumer.pause(topicPartition) { |ar_err,ar|

      if (ar_err == nil)

        puts "Paused"

        # resume read operation after a specific time
        vertx.set_timer(5000) { |timeId|

          # resumi read operations
          consumer.resume(topicPartition)
        }
      end
    }
  end
}

----

== Closing a consumer

Call close to close the consumer. Closing the consumer closes any open connections and releases all consumer resources.

The close is actually asynchronous and might not complete until some time after the call has returned. If you want to be notified
when the actual close has completed then you can pass in a handler.

This handler will then be called when the close has fully completed.

[source,ruby]
----
consumer.close() { |res_err,res|
  if (res_err == nil)
    puts "Consumer is now closed"
  else
    puts "close failed"
  end
}

----

== Sending messages to a topic

You can use  `link:../../yardoc/VertxKafkaClient/KafkaProducer.html#write-instance_method[write]` to send messages (records) to a topic.

The simplest way to send a message is to specify only the destination topic and the related value, omitting its key
or partition, in this case the messages are sent in a round robin fashion across all the partitions of the topic.

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer_record'

(0...5).each do |i|

  # only topic and message value are specified, round robin on destination partitions
  record = VertxKafkaClient::KafkaProducerRecord.create("test", "message_#{i}")

  producer.write(record)
end

----

You can receive message sent metadata like its topic, its destination partition and its assigned offset.

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer_record'

(0...5).each do |i|

  # only topic and message value are specified, round robin on destination partitions
  record = VertxKafkaClient::KafkaProducerRecord.create("test", "message_#{i}")

  producer.write(record) { |done_err,done|

    if (done_err == nil)

      recordMetadata = done
      puts "Message #{record.value()} written on topic=#{recordMetadata['topic']}, partition=#{recordMetadata['partition']}, offset=#{recordMetadata['offset']}"
    end

  }
end


----

When you need to assign a partition to a message, you can specify its partition identifier
or its key

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer_record'

(0...10).each do |i|

  # a destination partition is specified
  record = VertxKafkaClient::KafkaProducerRecord.create("test", nil, "message_#{i}", 0)

  producer.write(record)
end

----

Since the producers identifies the destination using key hashing, you can use that to guarantee that all
messages with the same key are sent to the same partition and retain the order.

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer_record'

(0...10).each do |i|

  # i.e. defining different keys for odd and even messages
  key = i % 2

  # a key is specified, all messages with same key will be sent to the same partition
  record = VertxKafkaClient::KafkaProducerRecord.create("test", Java::JavaLang::String.value_of(key), "message_#{i}")

  producer.write(record)
end

----

NOTE: the shared producer is created on the first `createShared` call and its configuration is defined at this moment,
shared producer usage must use the same configuration.

== Sharing a producer

Sometimes you want to share the same producer from within several verticles or contexts.

Calling `link:../../yardoc/VertxKafkaClient/KafkaProducer.html#create_shared-class_method[KafkaProducer.createShared]`
returns a producer that can be shared safely.

[source,ruby]
----
require 'vertx-kafka-client/kafka_producer'

# Create a shared producer identified by 'the-producer'
producer1 = VertxKafkaClient::KafkaProducer.create_shared(vertx, "the-producer", config)

# Sometimes later you can close it
producer1.close()

----

The same resources (thread, connection) will be shared between the producer returned by this method.

When you are done with the producer, just close it, when all shared producers are closed, the resources will
be released for you.

== Closing a producer

Call close to close the producer. Closing the producer closes any open connections and releases all producer resources.

The close is actually asynchronous and might not complete until some time after the call has returned. If you want to be notified
when the actual close has completed then you can pass in a handler.

This handler will then be called when the close has fully completed.

[source,ruby]
----
producer.close() { |res_err,res|
  if (res_err == nil)
    puts "Producer is now closed"
  else
    puts "close failed"
  end
}

----

== Getting topic partition information

You can call the `link:../../yardoc/VertxKafkaClient/KafkaProducer.html#partitions_for-instance_method[partitionsFor]` to get information about
partitions for a specified topic:

[source,ruby]
----

# asking partitions information about specific topic
producer.partitions_for("test") { |ar_err,ar|

  if (ar_err == nil)

    ar.each do |partitionInfo|
      puts partitionInfo
    end
  end
}

----

== Handling errors

Errors handling (e.g timeout) between a Kafka client (consumer or producer) and the Kafka cluster is done using
`link:../../yardoc/VertxKafkaClient/KafkaConsumer.html#exception_handler-instance_method[exceptionHandler]` or
`link:../../yardoc/VertxKafkaClient/KafkaProducer.html#exception_handler-instance_method[exceptionHandler]`

[source,ruby]
----

# setting handler for errors
consumer.exception_handler() { |e|
  puts "Error = #{e.get_message()}"
}

----

== Automatic clean-up in verticles

If you’re creating consumers and producer from inside verticles, those consumers and producers will be automatically
closed when the verticle is undeployed.

== Using Vert.x serializers/deserizaliers

Vert.x Kafka client comes out of the box with serializers and deserializers for buffers, json object
and json array.

In a consumer you can use buffers

[source,ruby]
----

# Creating a consumer able to deserialize to buffers
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.deserializer"] = "io.vertx.kafka.client.serialization.BufferDeserializer"
config["value.deserializer"] = "io.vertx.kafka.client.serialization.BufferDeserializer"
config["group.id"] = "my_group"
config["auto.offset.reset"] = "earliest"
config["enable.auto.commit"] = "false"

# Creating a consumer able to deserialize to json object
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.deserializer"] = "io.vertx.kafka.client.serialization.JsonObjectDeserializer"
config["value.deserializer"] = "io.vertx.kafka.client.serialization.JsonObjectDeserializer"
config["group.id"] = "my_group"
config["auto.offset.reset"] = "earliest"
config["enable.auto.commit"] = "false"

# Creating a consumer able to deserialize to json array
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.deserializer"] = "io.vertx.kafka.client.serialization.JsonArrayDeserializer"
config["value.deserializer"] = "io.vertx.kafka.client.serialization.JsonArrayDeserializer"
config["group.id"] = "my_group"
config["auto.offset.reset"] = "earliest"
config["enable.auto.commit"] = "false"

----

Or in a producer

[source,ruby]
----

# Creating a producer able to serialize to buffers
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.serializer"] = "io.vertx.kafka.client.serialization.BufferSerializer"
config["value.serializer"] = "io.vertx.kafka.client.serialization.BufferSerializer"
config["acks"] = "1"

# Creating a producer able to serialize to json object
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.serializer"] = "io.vertx.kafka.client.serialization.JsonObjectSerializer"
config["value.serializer"] = "io.vertx.kafka.client.serialization.JsonObjectSerializer"
config["acks"] = "1"

# Creating a producer able to serialize to json array
config = Hash.new()
config["bootstrap.servers"] = "localhost:9092"
config["key.serializer"] = "io.vertx.kafka.client.serialization.JsonArraySerializer"
config["value.serializer"] = "io.vertx.kafka.client.serialization.JsonArraySerializer"
config["acks"] = "1"

----

ifdef::java,groovy,kotlin[]
You can also specify the serizalizers/deserializers at creation time:

In a consumer

[source,ruby]
----
Code not translatable
----

Or in a producer

[source,ruby]
----
Code not translatable
----

endif::[]

ifdef::java[]
== RxJava API

The Kafka client provides an Rxified version of the original API.

[source,ruby]
----
Code not translatable
----
endif::[]

ifdef::java,groovy,kotlin[]
== Stream implementation and native Kafka objects

When you want to operate on native Kafka records you can use a stream oriented
implementation which handles native Kafka objects.

The `link:unavailable[KafkaReadStream]` shall be used for reading topic partitions, it is
a read stream of `link:unavailable[ConsumerRecord]` objects.

The `link:unavailable[KafkaWriteStream]` shall be used for writing to topics, it is a write
stream of `link:unavailable[ProducerRecord]`.

The API exposed by these interfaces is mostly the same than the polyglot version.
endif::[]